# Generated by Django 4.0.3 on 2022-04-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='default_name', max_length=100),
            preserve_default=False,
        ),
    ]
