# Generated by Django 4.0.4 on 2022-04-15 16:01

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_user_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManagerV2()),
            ],
        ),
    ]
